language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo64-9.0
  - Pharo64-8.0

matrix:
  fast_finish: true

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Pharo.image Pharo.changes

branches:
  except:
    - /^(?i:continuous)$/

