name: Continuous-development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: Moose-on-Pharo10
    strategy:
      matrix:
        smalltalk: [ Pharo64-10 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15

      - name: set-version
        run: |
          ls -l $SMALLTALK_CI_VM
          $SMALLTALK_CI_VM  $SMALLTALK_CI_IMAGE eval --save "MooseVersion current commitHash: '$GITHUB_SHA'. HelpBrowser allInstances do: #close. MooseWelcome openForRelease"
          
      - name: rename
        run: |
          mv $SMALLTALK_CI_BUILD/* .
          mv TravisCI.image $PROJECT_NAME.image
          mv TravisCI.changes $PROJECT_NAME.changes
          echo '100' > pharo.version
        
      - name: package
        run: |
          zip -r $PROJECT_NAME.zip $PROJECT_NAME.image $PROJECT_NAME.changes *.sources pharo.version
          ls

      - name: Update Release
        # You may pin to the exact commit or the version.
        # uses: johnwbyrd/update-release@1d5ec4791e40507e5eca3b4dbf90f0b27e7e4979
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: 'continuous'
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.PROJECT_NAME }}.zip
